name: Build & Deploy
on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Login to Github Container Registry
        run: echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin 
        
      - name: Cache npm
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - name: Build Docker Image
        run: docker build -t ghcr.io/sharknoon/pixina .
        env:
          FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}
        
      - name: Push Image to Registry
        run: docker push ghcr.io/sharknoon/pixina

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Remove existing Container
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: sudo docker stop pixina; sudo docker rm pixina; sudo docker rmi ghcr.io/sharknoon/pixina
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASS }}
   
      - name: Start new Container
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: echo ${{ secrets.GHCR_PAT }} | sudo docker login ghcr.io -u ${{ github.actor }} --password-stdin && sudo docker pull ghcr.io/sharknoon/pixina && sudo docker run -d --name pixina --network traefik-net -v pixina_config:/etc/nginx/conf.d --restart=always ghcr.io/sharknoon/pixina
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASS }}


